export const NAVIGATION_GOBACK = 'NAVIGATION_GOBACK';
export const NAVIGATION_NAVIGATE = 'NAVIGATION_NAVIGATE';
export const NAVIGATION_RESET = 'NAVIGATION_RESET';

export const TIMELINE_APPEND = 'TIMELINE_APPEND';
export const TIMELINE_PREPEND = 'TIMELINE_PREPEND';
export const TIMELINE_RESET = 'TIMELINE_RESET';
