export const NAVIGATION_GOBACK = 'NAVIGATION_GOBACK';
export const NAVIGATION_NAVIGATE = 'NAVIGATION_NAVIGATE';
export const NAVIGATION_RESET = 'NAVIGATION_RESET';

export const TIMELINE_APPEND = 'TIMELINE_APPEND';
export const TIMELINE_SET_LIKE_COUNT = 'TIMELINE_SET_LIKE_COUNT';
export const TIMELINE_SET_LIKES = 'TIMELINE_SET_LIKES';
export const TIMELINE_PREPEND = 'TIMELINE_PREPEND';
export const TIMELINE_RESET = 'TIMELINE_RESET';

export const USERS_ADD = 'USERS_ADD';
